name: Rodar Robo de Apostas

on:
  workflow_dispatch:

jobs:
  executar-robo:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar dependências atualizadas
      run: |
        python -m pip install --upgrade pip
        pip install requests google-genai

    - name: Executar o Robô de Apostas
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python robo.py
