name: Disparo Diario Robo Apostas

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rodar-robo]

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências necessárias
        run: |
          pip install requests google-genai

      - name: Executar Script do Robô
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_FOOTBALL_KEY_2: ${{ secrets.API_FOOTBALL_KEY_2 }}
        run: python robo.py
